name: Name
title: Title
markdown: kramdown
author: Name
baseurl: ""
url: ""
permalink: pretty
<<<<<<< HEAD
description: Description
=======
description: Hi! My name is Zaid Baghal and I am currently in my junior year at Rutgers University pursuing a degree in Computer Science. Some of my hobbies include running, drawing, photography, and filmmaking. I use this website as a portfolio/blog as well as a showcase for all the things I am working on. Parts of htis website are still under construction. Feel free to look around!
>>>>>>> parent of 24a0bb0... updates

kramdown: 
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: "_posts"
      type: posts
    values:
      layout: posts
      author: Name
      featured-img: /assets/blogposts/img/da-kraplak-727110-unsplash.jpg
      permalink: /:year/:month/:day/:title 
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: project
<<<<<<< HEAD
      featured-img: 
      github-link: 
=======
      featured-img: https://image.ibb.co/htduXz/malcolm_lightbody_698733_unsplash.jpg

>>>>>>> parent of 24a0bb0... updates
    
collections:
  projects:
    output: true
