name: Name
title: Title
markdown: kramdown
author: Name
baseurl: ""
url: ""
permalink: pretty
description: Description

kramdown: 
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: "_posts"
      type: posts
    values:
      layout: posts
      author: Name
      featured-img: /assets/blogposts/img/da-kraplak-727110-unsplash.jpg
      permalink: /:year/:month/:day/:title 
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: project
      featured-img: 
      github-link: 
    
collections:
  projects:
    output: true
