name: Zaid S. Baghal
title: Zaid S. Baghal
markdown: kramdown
author: Zaid S. Baghal
baseurl: ""
url: ""
permalink: pretty
description: Hi! My name is Zaid Baghal and I am currently in my junior year at Rutgers University pursuing a degree in Computer Science. Some of my hobbies include running, drawing, photography, and filmmaking. I use this website as a portfolio/blog as well as a showcase for all the things I am working on. Feel free to look around!

kramdown: 
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: "_posts"
      type: posts
    values:
      layout: posts
      author: Zaid S. Baghal
      featured-img: /assets/blogposts/img/da-kraplak-727110-unsplash.jpg
      permalink: /:year/:month/:day/:title 
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: project
      featured-img: https://image.ibb.co/htduXz/malcolm_lightbody_698733_unsplash.jpg

    
collections:
  projects:
    output: true
